version: '0'
services:
  web:
    build: .
    ports:
      - '3000:3000'
  api:
    image: json-server
    volumes:
      - ./db.json:/data/db.json
    command: json-server --watch /data/db.json --port 3001
    ports:
      - '3001:3001'